application:
  actions: actions
  web: web-src

packages:
  qsr:
    license: Apache-2.0
    actions:
      menu-provider:
        function: actions/menu-provider/index.js
        web: 'yes'
        runtime: nodejs:20
        annotations:
          require-adobe-auth: false
          final: true
        inputs:
          market: us
          CONTENT_SOURCE: aem
          LOG_LEVEL: info
          DATALOG_LEVEL: all

      store-provider:
        function: actions/store-provider/index.js
        web: 'yes'
        runtime: nodejs:20
        annotations:
          require-adobe-auth: false
          final: true
        inputs:
          market: us
          CONTENT_SOURCE: aem
          LOG_LEVEL: info
          DATALOG_LEVEL: all

      rewards-provider:
        function: actions/rewards-provider/index.js
        web: 'yes'
        runtime: nodejs:20
        annotations:
          require-adobe-auth: true
          final: true
        inputs:
          market: us
          CONTENT_SOURCE: aem
          LOG_LEVEL: info
          DATALOG_LEVEL: all

      user-provider:
        function: actions/user-provider/index.js
        web: 'yes'
        runtime: nodejs:20
        annotations:
          require-adobe-auth: true
          final: true
        inputs:
          market: us
          CONTENT_SOURCE: aem
          LOG_LEVEL: info
          DATALOG_LEVEL: all

      bff-proxy:
        function: actions/bff-proxy/index.js
        web: 'yes'
        runtime: nodejs:20
        annotations:
          require-adobe-auth: true
          final: true
        inputs:
          market: us
          CONTENT_SOURCE: aem
          LOG_LEVEL: info
          DATALOG_LEVEL: all

      device-provider:
        function: actions/device-provider/index.js
        web: 'yes'
        runtime: nodejs:20
        annotations:
          require-adobe-auth: false
          final: true
        inputs:
          market: us
          CONTENT_SOURCE: aem
          LOG_LEVEL: info
          DATALOG_LEVEL: all

      webhook:
        function: actions/webhook/index.js
        web: 'yes'
        runtime: nodejs:20
        annotations:
          require-adobe-auth: true
          final: true
        inputs:
          CONTENT_SOURCE: aem
          LOG_LEVEL: info
          DATALOG_LEVEL: all

      sitemap-generator:
        function: actions/sitemap-generator/index.js
        web: 'yes'
        runtime: nodejs:20
        annotations:
          require-adobe-auth: true
          final: true
        inputs:
          market: us
          CONTENT_SOURCE: aem
          push: true
          LOG_LEVEL: info
          DATALOG_LEVEL: all
